config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :admins, only: :index
  
  resources :artistes, param: :name do 
    collection do 
      get 'display'
    end
  end
  resources :contact_us, only: [:new, :create]
  
  resources :events, param: :title do 
    collection do 
      get 'display'
    end
  end

  resources :press_articles, path: 'articles', param: :title do 
    collection do
      get 'display'
    end
  end

  resources :partners, except: [:show] do 
    collection do
      get 'display'
    end
  end

  get 'legal_notes' => 'static_pages#legal_notes'
  get 'about' => 'static_pages#about'
  get 'site_map' => 'static_pages#site_map'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  root to: "home#index", defaults: { format: 'html' }
end

app/models/artiste.rb
class Artiste < ActiveRecord::Base
  extend FriendlyId
  mount_uploader :slideshow_image, SlideshowUploader
  mount_uploader :presentation_image, ArtisteUploader

  has_many :works, dependent: :destroy
  has_many :sounds, dependent: :destroy

  accepts_nested_attributes_for :works, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :sounds, reject_if: :all_blank, allow_destroy: true

  before_validation :reset_slug

  friendly_id :alias_or_full_name, use: [:slugged, :history]

  validates :last_name, :first_name, :presentation_image, presence: true
  validates :last_name, uniqueness: { scope: :first_name }
  validates :alias, uniqueness: true, allow_blank: true


  def alias_or_full_name
    if self.alias.present?
      self.alias
    else
      "#{first_name} #{last_name}"
    end 
  end

  def full_name_or_alias_changed?
    self.alias_changed? || self.first_name_changed? || self.last_name_changed?
  end


  def self.filter_artistes(type)
    if type == 'music'
      Artiste.includes(:sounds).where(to_display: true).where("sounds.id IS NOT NULL").order(:last_name).references(:sounds)
    elsif type.present?
      Artiste.includes(:works).where(to_display: true, works: {type_file: type}).order(:last_name)
    else
      Artiste.includes(:works).where(to_display: true).order(:last_name)
    end
  end

  def full_name_downcased
    "#{first_name} #{last_name}".downcase
  end

  def self.display_title(type)
    if type == "photo"
      "Photographes"
    elsif type == "sculpture"
      "Sculpteurs"
    elsif type == "music"
      "Musiciens"
    elsif type == "painting"
      "Peintres"
    else
      "Artistes"
    end
  end

  private 
    def reset_slug
      if self.full_name_or_alias_changed?
        self.slug = nil
      end
    end
end

app/controllers/artistes_controller.rb
class ArtistesController < ApplicationController
  before_action :authenticate_admin!, except: [:display, :show]
  before_action :set_artiste, only: [:show, :edit, :update, :destroy]

  respond_to(:html)

  def index 
    @artistes = Artiste.includes(:works).order(:last_name)
    @response = { artistes: @artistes, visited: "admin", tab: "artistes"}
    render template: 'admins/index'
  end

  def display
    @artistes = Artiste.filter_artistes(params[:type])
    title = Artiste.display_title(params[:type])
    @response = { visited: "artistes", title: title }
  end

  def show
    @response = { visited: "artistes" }
  end

  def new
    @artiste = Artiste.new
    @work = @artiste.works.build
    respond_with(@artiste)
  end

  def edit
  end

  def create
    @artiste = Artiste.new(artiste_params)
    @artiste.save
    respond_with(@artiste, location: artistes_path)
  end

  def update
    @artiste.update(artiste_params)
    respond_with(@artiste, location: artistes_path)
  end

  def destroy
    @artiste.destroy
    redirect_to action: :index
  end

  private
    def set_artiste
      @artiste = Artiste.friendly.preload(:works).find(params[:name])
    end

    def artiste_params
      allowed_params = 
        [
          :last_name, 
          :first_name, 
          :alias, 
          :slideshow_image, 
          :slideshow_biography, 
          :biography, 
          :on_display, 
          :to_display, 
          :presentation_image, 
          :slideshow_position,
          :next_exhibition,
          works_attributes: 
          [
            :title, 
            :type_file, 
            :file, 
            :id, 
            :_destroy
          ],
          sounds_attributes:
          [
            :title,
            :file,
            :id,
            :_destroy
          ]
        ]

      params.require(:artiste).permit(allowed_params)
    end

end

app/helpers/artistes_helper.rb
module ArtistesHelper
end

app/views/artistes/_form.html.haml
= simple_form_for(@artiste, html: { class: 'smart-green' }) do |f|
  %h1= params[:action] == "new" ? "Nouvel Artiste" : "Editer Artiste"

  .field
    = f.label :to_display, "Afficher"
    = f.check_box :to_display, checked: Proc.new { |f| params[:action] == 'edit' ? f.object.to_display : true }.call(f)
  .field
    = f.input :last_name, label: "Nom"
  .field
    = f.input :first_name, label: "Prénom"
  .field
    = f.label :alias
    = f.text_field :alias
  .field
    = f.label :slideshow_image, "Image du slideshow (Largeur: 450px)"
    = f.file_field :slideshow_image
    - if params[:action] == 'edit'
      %br
      = image_tag(f.object.slideshow_image_url(:thumb_150)) if f.object.slideshow_image?
  .field
    = f.label :slideshow_biography, "Slideshow biographie"
    = f.text_area :slideshow_biography, :cols => 90, :rows => 5
  .field
    = f.label :slideshow_position, "Slideshow position"
    = f.select :slideshow_position, 1..10, include_blank: true
  .field
    = f.label :on_display, "Afficher sur le slideshow"
    = f.check_box :on_display
  .field
    = f.input :presentation_image, label: "Image de présentation (Dimension: 250px x 250px)"
    - if params[:action] == 'edit'
      %br
      = image_tag(f.object.presentation_image_url(:thumb_150)) if f.object.presentation_image?
  .field
    = f.label :biography, "Biographie"
    = f.text_area :biography, :cols => 90, :rows => 10
  .field
    = f.label :next_exhibition, "Prochaine exposition"
    = f.text_area :next_exhibition, :cols => 90, :rows => 5
  .dash
  #works
    .field
      = f.fields_for :works do |work|
        = render 'work_fields', f: work
    .links
      = link_to_add_association 'Ajouter une image', f, :works, class: "button inline-block"
      .clear.dash
  #sounds
    .field
      = f.fields_for :sounds do |sound|
        = render 'sound_fields', f: sound
    .links
      = link_to_add_association 'Ajouter un son', f, :sounds, class: "button inline-block"
      .clear.dash
  .actions
    = f.submit 'Save', class: "button"

app/views/artistes/_index.html.haml
%table
  %thead
    %tr
      %th Nom
      %th Prénom
      %th Alias
      %th Slideshow image
      %th Slideshow biographie
      %th Image présentation 
      %th Biogragphie
      %th
      %th
      
  %tbody
    - @artistes.each do |artiste|
      %tr
        %td= link_to artiste.last_name, artiste
        %td= link_to artiste.first_name, artiste
        %td= artiste.alias
        %td= image_tag(artiste.slideshow_image_url(:thumb)) if artiste.slideshow_image?
        %td= truncate(artiste.slideshow_biography, length: 50, separator: ' ')
        %td= image_tag(artiste.presentation_image_url(:thumb)) if artiste.presentation_image?
        %td= truncate(artiste.biography, length: 200, separator: ' ')
        %td= link_to 'Editer', edit_artiste_path(artiste)
        %td= link_to 'Supprimer', artiste, :method => :delete, :data => { :confirm => 'Êtes-vous sûr ?' }

%br

= link_to 'Nouvel Artiste', new_artiste_path

app/views/artistes/_sound_fields.html.haml
.nested-fields
  .field
    = f.input       :title, label: "Titre du son"
  .field
    = f.label       :file, "Upload son"
    = f.file_field  :file
  .field
  - if params[:action] == 'edit'
    %br
    = link_to File.basename(f.object.file.path), f.object.file_url, target: :_blank  if f.object.file? && f.object.file.path
    = link_to_remove_association "Retirer ce son", f, class: "button inline-block"
  .clear

    

app/views/artistes/_work_fields.html.haml
.nested-fields
  .field
    = f.input       :title, label: "Titre du l'oeuvre"
  .field
    = f.label       :type_file, "Type de l'oeuvre"
    = f.select      :type_file, Work::TYPE_FILE
  .field
    = f.label       :file, "Upload image"
    = f.file_field  :file
  .field
  - if params[:action] == 'edit'
    %br
    = image_tag(f.object.file_url(:thumb_150)) if f.object.file?
  = link_to_remove_association "Retirer cette image", f, class: "button inline-block"
  .clear
    

app/views/artistes/display.html.haml
#artistes
  %h1= "Les #{@response[:title]}"
  #content-block
    - @artistes.each do |artiste|
      %div.block-left
        = link_to image_tag(artiste.presentation_image_url(:thumb_150), width: "150px", height: "150px"), artiste
        %div.center.full_name
          - if artiste.alias.present? 
            = link_to "<span>#{artiste.alias}</span>".html_safe, artiste, class: "align-top-margin"
          - else
            = link_to "<span>#{artiste.first_name} <br/> #{artiste.last_name}</span>".html_safe, artiste
    .clear

app/views/artistes/edit.html.haml
= render 'form'

= link_to 'Back', artistes_path

app/views/artistes/new.html.haml
= render 'form'

= link_to 'Back', admins_path

app/views/artistes/show.html.haml
#artiste
  %h1
    = @artiste.alias_or_full_name
  #content-block
    .left.margin-right.margin-bottom= image_tag(@artiste.presentation_image_url, width: "250px", height: "250px")
    %p.no-margin.first_line.big-line-height= format_text(@artiste.biography)
    
    - if @artiste.next_exhibition.present?
      %br
      %h4.clear Prochaine exposition
      %p= format_text(@artiste.next_exhibition)

    - if @artiste.works.any?
      %br
      %h4.clear Découvrez ses oeuvres
      #work-block
        - @artiste.works.each do |work|
          .container_img= image_tag work.file_url, class: "image_gallery" , href: work.file_url       

    .clear
    
    - if @artiste.sounds.any?
      %h4.clear Découvrez ses compositions
      %br
      #sound-block
        #jplayer.jp-jplayer
        #jp_container.jp-audio{"aria-label" => "media player", role: "application"}
          .jp-type-single
            .jp-gui.jp-interface
              .jp-volume-controls
                %button.jp-mute{role: "button", tabindex: "0"} mute
                %button.jp-volume-max{role: "button", tabindex: "0"} max volume
                .jp-volume-bar
                  .jp-volume-bar-value
              .jp-controls-holder
                .jp-controls
                  %button.jp-play{role: "button", tabindex: "0"} play
                  %button.jp-stop{role: "button", tabindex: "0"} stop
                .jp-progress
                  .jp-seek-bar
                    .jp-play-bar
                .jp-current-time{"aria-label" => "time", role: "timer"}  
                .jp-duration{"aria-label" => "duration", role: "timer"}  
                .jp-toggles
                  %button.jp-repeat{role: "button", tabindex: "0"} repeat
            .jp-details
              .jp-title{"aria-label" => "title"}  
            .jp-no-solution
              %span Update Required
              To play the media you will need to either update your browser to a recent version or update your
              = succeed "." do
                %a{href: "http://get.adobe.com/flashplayer/", target: "_blank"} Flash plugin
        
        #sound-links
          - @artiste.sounds.each do |sound|
            = link_to sound.title, sound.file_url, class: 'play'    

      .clear

      :javascript
        $(document).ready(function(){
          $("#jplayer").jPlayer({
            ready: function () {
              var media = $(".play").first()
              setMedia(media.text(), media.attr("href"));
            },
            cssSelectorAncestor: "#jp_container",
            swfPath: "/js",
            supplied: "mp3, m4a",
            useStateClassSkin: true,
            autoBlur: true,
            smoothPlayBar: false,
            keyEnabled: true,
            remainingDuration: true,
            toggleDuration: true,
            volume: 0.5
          });
        
          $(".play").click(function(e) {
            e.preventDefault();
            setMedia($(this).text(), $(this).attr("href"));
            $("#jplayer").jPlayer('play');
          });

          function setMedia(filename, href) {
            var ext = href.split('.').pop();
            if (ext == "m4a") {
              $("#jplayer").jPlayer("setMedia", {
                m4a: href,
                title: filename
              });
            }
            else {
              $("#jplayer").jPlayer("setMedia", {
                mp3: href,
                title: filename
              });
            }
          }
        });