config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :admins, only: :index
  
  resources :artistes, param: :name do 
    collection do 
      get 'display'
    end
  end
  resources :contact_us, only: [:new, :create]
  
  resources :events, param: :title do 
    collection do 
      get 'display'
    end
  end

  resources :press_articles, path: 'articles', param: :title do 
    collection do
      get 'display'
    end
  end

  resources :partners, except: [:show] do 
    collection do
      get 'display'
    end
  end

  get 'legal_notes' => 'static_pages#legal_notes'
  get 'about' => 'static_pages#about'
  get 'site_map' => 'static_pages#site_map'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  root to: "home#index", defaults: { format: 'html' }
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artiste.rb
class Artiste < ActiveRecord::Base
  extend FriendlyId
  mount_uploader :slideshow_image, SlideshowUploader
  mount_uploader :presentation_image, ArtisteUploader

  has_many :works, dependent: :destroy
  has_many :sounds, dependent: :destroy

  accepts_nested_attributes_for :works, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :sounds, reject_if: :all_blank, allow_destroy: true

  before_validation :reset_slug

  friendly_id :alias_or_full_name, use: [:slugged, :history]

  validates :last_name, :first_name, :presentation_image, presence: true
  validates :last_name, uniqueness: { scope: :first_name }
  validates :alias, uniqueness: true, allow_blank: true


  def alias_or_full_name
    if self.alias.present?
      self.alias
    else
      "#{first_name} #{last_name}"
    end 
  end

  def full_name_or_alias_changed?
    self.alias_changed? || self.first_name_changed? || self.last_name_changed?
  end


  def self.filter_artistes(type)
    if type == 'music'
      Artiste.includes(:sounds).where(to_display: true).where("sounds.id IS NOT NULL").order(:last_name).references(:sounds)
    elsif type.present?
      Artiste.includes(:works).where(to_display: true, works: {type_file: type}).order(:last_name)
    else
      Artiste.includes(:works).where(to_display: true).order(:last_name)
    end
  end

  def full_name_downcased
    "#{first_name} #{last_name}".downcase
  end

  def self.display_title(type)
    if type == "photo"
      "Photographes"
    elsif type == "sculpture"
      "Sculpteurs"
    elsif type == "music"
      "Musiciens"
    elsif type == "painting"
      "Peintres"
    else
      "Artistes"
    end
  end

  private 
    def reset_slug
      if self.full_name_or_alias_changed?
        self.slug = nil
      end
    end
end

app/models/contact_us.rb
class ContactUs < ActiveRecord::Base  
  validates :last_name, :first_name, :email, :object, :message, presence: true
  validates :email, email: { message: I18n.t('errors.messages.email') }

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :slideshow_image, EventUploader

  validates :title, :start_date, :end_date, presence: true
  validates :title, uniqueness: true
  
  def self.filter_events(type, in_time)
    if type.present?
      if in_time.present?
        Event.where(to_display: true, type_event: type).where('end_date < ?', DateTime.yesterday.end_of_day).order('start_date DESC')
      else
        Event.where(to_display: true, type_event: type).where('end_date >= ?', DateTime.yesterday.end_of_day).order(:start_date)
      end
    else
      if in_time.present?
        Event.where(to_display: true).where('end_date < ?', DateTime.yesterday.end_of_day).order('start_date DESC')
      else
        Event.where(to_display: true).where('end_date >= ?', DateTime.yesterday.end_of_day).order(:start_date)
      end
    end
  end


  def self.set_calendar(events, event_name)
    cal = Clndr.new(event_name)
    events.each do |event|
      cal.add_multiday_event(event.start_date, event.end_date, event.title)
    end
    cal
  end

end

app/models/home.rb
class Home < ActiveRecord::Base

  def self.slideshow_collection
    collection = Artiste.where(on_display: true, to_display: true).order(:slideshow_position)
    collection = collection + Event.where(on_display: true, to_display: true).where('end_date >= ?', DateTime.yesterday.end_of_day).order(:slideshow_position) 
    
    collection.sort!{|a,b| a.slideshow_position && b.slideshow_position ? a.slideshow_position <=> b.slideshow_position : a.slideshow_position ? -1 : 1}
  end

end

app/models/partner.rb
class Partner < ActiveRecord::Base
  mount_uploader :image, PartnerUploader

  validates :name, :website, :description, :image, presence: true
  validates :name, uniqueness: true
end

app/models/press_article.rb
class PressArticle < ActiveRecord::Base
  extend FriendlyId
  before_validation :reset_slug

  friendly_id :title, use: [:slugged, :history]

  mount_uploader :photo, PressArticleUploader

  validates :title, :short_paragraph, :paragraph, presence: true
  validates :title, uniqueness: true

  private 
    def reset_slug
      if self.title_changed?
        self.slug = nil
      end
    end
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  mount_uploader :file, SoundUploader

  belongs_to :artiste
  validates :title, presence: true, uniqueness: true
end

app/models/work.rb
class Work < ActiveRecord::Base
  mount_uploader :file, WorkUploader

  belongs_to :artiste
  validates :title, presence: true, uniqueness: true


  TYPE_FILE = [["Peinture","painting"],["Photographie", "photo"],["Sculpture","sculpture"]]

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  respond_to :html

  def index
    @admins = Admin.all.order(:email)
    @response = { admins: @admins, visited: "admin", from: "admins"}
    respond_with(@response)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  respond_to :html

  def index
    @slideshow_collection = Home.slideshow_collection 
    @response = { visited: "home"}
    respond_with(@response)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_active?(visited, link)
    if visited == link
      "active"
    elsif visited == link
      "active"
    end
  end

  def render_html(text)
    Haml::Engine.new(text).render
  end

  def format_text(text)
    text.gsub(/\n/, "<br/>").html_safe
  end

  def display_filename(filename)
    filename.split("/").last.split(".")[0..-2].join(".")
  end
end

app/helpers/artistes_helper.rb
module ArtistesHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def cache_key_for_slideshow_collection
    
    displayed_artists     = Artiste.where(on_display: true, to_display: true)
    count_artists         = displayed_artists.count
    max_updated_at_artist = displayed_artists.maximum(:updated_at).try(:utc).try(:to_s, :number)
    
    displayed_events      = Event.where(on_display: true, to_display: true).where('end_date >= ?', DateTime.yesterday.end_of_day)
    count_events          = displayed_events.count
    max_updated_at_event  = displayed_events.maximum(:updated_at).try(:utc).try(:to_s, :number)

    "slideshow/all-artists-#{count_artists}-#{max_updated_at_artist}-events-#{count_events}-#{max_updated_at_event}"
  end

end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/_index.html.haml
%table
  %thead
    %tr
      %th Email
      %th Créé le
      %th
      %th
      
  %tbody
    - @admins.each do |admin|
      %tr
        %td= admin.email
        %td= l admin.created_at, formats: :short
        %td
          = link_to 'Editer', edit_admin_registration_path
        %td
          = link_to 'Supprimer', cancel_admin_registration_path, data: { confirm: 'Êtes-vous sûr ?' } unless Admin.count == 1

%br

=# link_to 'Nouvel Admin', new_admin_registration_path

app/views/admins/index.html.haml
.admin-links  
  = link_to "Artistes" ,  artistes_path, class: (link_active?(@response[:from], nil))
  = link_to "évènements", events_path, class: (link_active?(@response[:from], "events"))
  = link_to "Presse" ,    press_articles_path, class: (link_active?(@response[:from], "press_articles"))
  = link_to "Partenaires", partners_path, class: (link_active?(@response[:from], "partners"))
  = link_to "Admins" ,    admins_path, class: (link_active?(@response[:from], "admins"))


- if @response[:from] == "events"
  = render partial: "events/index"
- elsif @response[:from] == "press_articles"
  = render partial: "press_articles/index"
- elsif @response[:from] == "partners"
  = render partial: "partners/index"
-elsif @response[:from] == "admins"
  = render partial: "admins/index"
- else
  = render partial: "artistes/index"

app/views/layouts/_footer.html.haml
#footer-content
  #footer-menu
    %h3 Liens pratiques
    = render 'layouts/navigation'

  #footer-horaires    
    %h3 Nos horaires d'ouverture
    #horaires-ouverture
      %em La galerie est ouverte :
      %br 
        Le Mercredi et le Jeudi de 17h00 à 20h00
        %br Le Vendredi de 17h00 à 20h00
        Le Samedi de 15h00 à 20h00
      %br
    .footer-social.hidden
      %h3 Restez en contact
      .custom-footer-socials
        .btn_newsletter
          %a#btn_newsletter{href: "#"} Abonnez-vous à notre newsletter
  #footer-contact
    %h3 Contactez-nous
    #contact-us
      #localisation
        EXCENTRIC
        %br 9, rue du commerce - 59600 Maubeuge
        #mail maubeuge.excentric@gmail.com
    
    %br
    %h3 Suivez-nous
    .fb-like{"data-action" => "like", "data-href" => "https://www.facebook.com/pages/Excentric-Maubeuge/392047360986940", "data-layout" => "standard", "data-share" => "false", "data-show-faces" => "true", "data-width" => "245", "data-colorscheme" => "dark"}
    .hidden= link_to image_tag("social/twitter.png", height: "48px"), ""

  .clear    
#footer-links
  = link_to "Mentions légales", legal_notes_path
  = "-"
  = link_to "Plan du site", site_map_path
  = "-&nbsp".html_safe
  Copyright © 2015 Excentric Maubeuge - réalisé par Thomas Egret
  
#fb-root

app/views/layouts/_navigation.html.haml
%ul#menu
  %li
    = link_to "Accueil", root_path, class: (link_active?(@response[:visited], "home") if @response)
  %li 
    =link_to "Actualités", display_events_path, class: (link_active?(@response[:visited], "news") if @response)
    %ul
      %li
        = link_to "Expositions", display_events_path(type: "exhibition")
      %li
        = link_to "évènements", display_events_path(type: "event")
      %li
        = link_to "Presse", display_press_articles_path
  %li
    = link_to "Les artistes", display_artistes_path, class: (link_active?(@response[:visited], "artistes") if @response)
    %ul
      %li
        = link_to "Musiciens", display_artistes_path(type: "music")
      %li
        = link_to "Peintres", display_artistes_path(type: "painting")
      %li
        = link_to "Photographes", display_artistes_path(type: "photo")
      %li
        = link_to "Sculpteurs", display_artistes_path(type: "sculpture")
  %li
    = link_to "à propos", about_path, class: (link_active?(@response[:visited], "about") if @response)
    %ul
      %li
        = link_to "Partenaires", display_partners_path
  %li
    = link_to "Contactez-nous", new_contact_us_path, class: (link_active?(@response[:visited], "contact") if @response)
  
  - if admin_signed_in?
    %li
      = link_to "Admin", artistes_path, class: (link_active?(@response[:visited], "admin") if @response)
      %ul
        %li
          = link_to "Artistes", artistes_path
        %li
          = link_to "évènements", events_path
        %li
          = link_to "Presse", press_articles_path
        %li
          = link_to "Partenaires", partners_path
        %li
          = link_to "Se Déconnecter", destroy_admin_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Excentric"
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{src: "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", type: "text/javascript"}
    %script{src: "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", type: "text/javascript"}
    = csrf_meta_tags 
%body
  %header
    = link_to image_tag("logo.png"), root_url
  %nav
    = render 'layouts/navigation'

  #middle
    / Use a container to wrap the slider, the purpose is to enable slider to always fit width of the wrapper while window resize
    .container_2
      = yield 

  %footer
    = render 'layouts/footer'