config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :admins, only: :index
  
  resources :artistes, param: :name do 
    collection do 
      get 'display'
    end
  end
  resources :contact_us, only: [:new, :create]
  
  resources :events, param: :title do 
    collection do 
      get 'display'
    end
  end

  resources :press_articles, path: 'articles', param: :title do 
    collection do
      get 'display'
    end
  end

  resources :partners, except: [:show] do 
    collection do
      get 'display'
    end
  end

  get 'legal_notes' => 'static_pages#legal_notes'
  get 'about' => 'static_pages#about'
  get 'site_map' => 'static_pages#site_map'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  root to: "home#index", defaults: { format: 'html' }
end

app/models/home.rb
class Home < ActiveRecord::Base

  def self.slideshow_collection
    collection = Artiste.where(on_display: true, to_display: true).order(:slideshow_position)
    collection = collection + Event.where(on_display: true, to_display: true).where('end_date >= ?', DateTime.yesterday.end_of_day).order(:slideshow_position) 
    
    collection.sort!{|a,b| a.slideshow_position && b.slideshow_position ? a.slideshow_position <=> b.slideshow_position : a.slideshow_position ? -1 : 1}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  respond_to :html

  def index
    @slideshow_collection = Home.slideshow_collection 
    @response = { visited: "home"}
    respond_with(@response)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def cache_key_for_slideshow_collection
    
    displayed_artists     = Artiste.where(on_display: true, to_display: true)
    count_artists         = displayed_artists.count
    max_updated_at_artist = displayed_artists.maximum(:updated_at).try(:utc).try(:to_s, :number)
    
    displayed_events      = Event.where(on_display: true, to_display: true).where('end_date >= ?', DateTime.yesterday.end_of_day)
    count_events          = displayed_events.count
    max_updated_at_event  = displayed_events.maximum(:updated_at).try(:utc).try(:to_s, :number)

    "slideshow/all-artists-#{count_artists}-#{max_updated_at_artist}-events-#{count_events}-#{max_updated_at_event}"
  end

end

app/views/home/index.html.haml
- cache cache_key_for_slideshow_collection do
  / Jssor Slider Begin
  #slider1_container

    / Loading Screen
    %div{:style => "position: absolute;", :u => "loading"}
      %div{class: "bg-loading"}
      %div{class: "gif-loading"}
    

    / Slides Container
    %div{:style => "cursor: move; width: 1000px; left: 56px; top: 0px; height: 450px; overflow: hidden;", :u => "slides"}
      - @slideshow_collection.each do |slideshow_object|
        - cache slideshow_object do
          - if slideshow_object.is_a? Event
            - title = slideshow_object.title
            - description = slideshow_object.slideshow_description
            - link_path = event_path(slideshow_object)
            - link_label = "Voir la suite"
          - else
            - title = slideshow_object.alias_or_full_name
            - description = slideshow_object.slideshow_biography
            - link_path = artiste_path(slideshow_object)
            - link_label = "Découvrir l'artiste"
          %div
            %img{:src2 => slideshow_object.slideshow_image.url, :u => "image"}/
            %img{:src => asset_path('bg-slideshow.png'), :u => "image", class: "bg-slideshow"}
            .block-text
              %h4
                = title
              .slideshow-text
                %br
                = description
                %br
                = link_to link_label, link_path
      
      / Arrow Left
      %span.jssora02l{:style => "width: 55px; height: 55px;left: 8px;", :u => "arrowleft"}
      / Arrow Right
      %span.jssora02r{:style => "width: 55px; height: 55px;right: 8px;", :u => "arrowright"}
    
    / bullet navigator container
    .jssorb13{:style => "position: absolute; bottom: 16px; ", :u => "navigator"}
      / bullet navigator item prototype
      %div{:style => "position: absolute; width: 16px; height: 16px;", :u => "prototype"}

  :javascript 
    $(document).ready(function(){
      var _SlideshowTransitions = [
      //Fade
      { $Duration: 1200, $Opacity: 2 }
      ];

      var options = {
        $FillMode: 2,                                       //[Optional] The way to fill image in slide, 0 stretch, 1 contain (keep aspect ratio and put all inside slide), 2 cover (keep aspect ratio and cover whole slide), 4 actual size, 5 contain for large image, actual size for small image, default value is 0      
        $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
        $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
        $AutoPlayInterval: 6000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
        $PauseOnHover: 1,                                   //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

        $ArrowKeyNavigation: true,                          //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
        $SlideEasing: $JssorEasing$.$EaseOutQuint,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
        $SlideDuration: 1200,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
        $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
        //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
        //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
        $SlideSpacing: 0,                                   //[Optional] Space between each slide in pixels, default value is 0
        $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
        $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
        $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
        $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
        $DragOrientation: 1,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

        $SlideshowOptions: { //[Optional] Options to specify and enable slideshow or not
          $Class: $JssorSlideshowRunner$, //[Required] Class to create instance of slideshow
          $Transitions: _SlideshowTransitions, //[Required] An array of slideshow transitions to play slideshow
          $TransitionsOrder: 1, //[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
          $ShowLink: true //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
        },

        $ArrowNavigatorOptions: {                           //[Optional] Options to specify and enable arrow navigator or not
          $Class: $JssorArrowNavigator$,                  //[Requried] Class to create arrow navigator instance
          $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
          $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
          $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1
          $Scale: false,                                  //Scales bullets navigator or not while slider scale
        },

        $BulletNavigatorOptions: {                                //[Optional] Options to specify and enable navigator or not
          $Class: $JssorBulletNavigator$,                       //[Required] Class to create navigator instance
          $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
          $AutoCenter: 1,                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
          $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1
          $Lanes: 1,                                      //[Optional] Specify lanes to arrange items, default value is 1
          $SpacingX: 12,                                   //[Optional] Horizontal space between each item in pixel, default value is 0
          $SpacingY: 4,                                   //[Optional] Vertical space between each item in pixel, default value is 0
          $Orientation: 1,                                //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
          $Scale: false,                                  //Scales bullets navigator or not while slider scale
        }
      };

      //Make the element 'slider1_container' visible before initialize jssor slider.
      $("#slider1_container").css("display", "block");
      var jssor_slider1 = new $JssorSlider$("slider1_container", options);

      //responsive code begin
      //you can remove responsive code if you don't want the slider scales while window resizes
      function ScaleSlider() {
        var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
        if (parentWidth) {
          jssor_slider1.$ScaleWidth(parentWidth - 30);
        }
        else
          window.setTimeout(ScaleSlider, 30);
      }
      ScaleSlider();

      $(window).bind("load", ScaleSlider);
      $(window).bind("resize", ScaleSlider);
      $(window).bind("orientationchange", ScaleSlider);
      //responsive code end
    });
    