config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :admins, only: :index
  
  resources :artistes, param: :name do 
    collection do 
      get 'display'
    end
  end
  resources :contact_us, only: [:new, :create]
  
  resources :events, param: :title do 
    collection do 
      get 'display'
    end
  end

  resources :press_articles, path: 'articles', param: :title do 
    collection do
      get 'display'
    end
  end

  resources :partners, except: [:show] do 
    collection do
      get 'display'
    end
  end

  get 'legal_notes' => 'static_pages#legal_notes'
  get 'about' => 'static_pages#about'
  get 'site_map' => 'static_pages#site_map'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  root to: "home#index", defaults: { format: 'html' }
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :slideshow_image, EventUploader

  validates :title, :start_date, :end_date, presence: true
  validates :title, uniqueness: true
  
  def self.filter_events(type, in_time)
    if type.present?
      if in_time.present?
        Event.where(to_display: true, type_event: type).where('end_date < ?', DateTime.yesterday.end_of_day).order('start_date DESC')
      else
        Event.where(to_display: true, type_event: type).where('end_date >= ?', DateTime.yesterday.end_of_day).order(:start_date)
      end
    else
      if in_time.present?
        Event.where(to_display: true).where('end_date < ?', DateTime.yesterday.end_of_day).order('start_date DESC')
      else
        Event.where(to_display: true).where('end_date >= ?', DateTime.yesterday.end_of_day).order(:start_date)
      end
    end
  end


  def self.set_calendar(events, event_name)
    cal = Clndr.new(event_name)
    events.each do |event|
      cal.add_multiday_event(event.start_date, event.end_date, event.title)
    end
    cal
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_admin!, except: [:display, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html
  def index
    @events = Event.all.order(:start_date)
    @response = { events: @events, visited: "admin", from: "events"}
    render template: 'admins/index'
  end

  def display
    @events = Event.filter_events(params[:type], params[:in_time])
    @response = { visited: "news"}
    @event_clndr = Event.set_calendar(@events, :events_calendar)
  end

  def show
    @response = { visited: "news" }
    @event_clndr = Event.set_calendar([@event], :events_calendar)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event, location: events_path)
  end

  def update
    @event.update(event_params)
    respond_with(@event, location: events_path)
  end

  def destroy
    @event.destroy
    redirect_to action: :index
  end

  private
    def set_event
      @event = Event.find(params[:title])
    end

    def event_params
      params.require(:event).permit(:title, :slideshow_image, :short_description, :description, :start_date, :end_date, :to_display, :on_display, :slideshow_description, :type_event, :slideshow_position)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for(@event, html: { class: 'smart-green' }) do |f|

  %h1= params[:action] == "new" ? "Nouvel Evènement" : "Editer Evènement" 

  .field
    = f.label :to_display, "Afficher"
    = f.check_box :to_display, checked: Proc.new { |f| params[:action] == 'edit' ? f.object.to_display : true }.call(f)
  .field
    = f.label :type_event, "Type d'évènement"
    = f.select :type_event, [["Evènement", "event"],["Exposition", "exhibition"]]
  .field
    = f.input :title, label: "Titre"
  .field
    / datepickerFromDate needed because of bug when trying switch months on first datepicker with two datepicker on same page
    = f.input :start_date, label: "Date de début", input_html: {class: "datetimepicker", id: "datepickerFromDate"}, as: :string
  .field
    = f.input :end_date, label: "Date de début", input_html: {class: "datetimepicker"}, as: :string
  .field
    = f.label :slideshow_image
    = f.file_field :slideshow_image
    - if params[:action] == 'edit'
      %br
      = image_tag(f.object.slideshow_image_url(:thumb)) if f.object.slideshow_image?
  .field
    = f.label :slideshow_description, "Slideshow description"
    = f.text_area :slideshow_description, :cols => 90, :rows => 5
  .field
    = f.label :slideshow_position, "Slideshow position"
    = f.select :slideshow_position, 1..10, include_blank: true
  .field
    = f.label :on_display, "Afficher sur le slideshow"
    = f.check_box :on_display
  .field
    = f.input :short_description, label: "Courte description", :cols => 90, :rows => 5
  .field
    = f.input :description, label: "Description", :cols => 90, :rows => 10
  .actions
    = f.submit 'Save', class: "button"

app/views/events/_index.html.haml
%table
  %thead
    %tr
      %th Titre
      %th Slideshow image
      %th Slideshow description
      %th Date de début
      %th Date de fin
      %th
      %th
      
  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= image_tag(event.slideshow_image_url(:thumb)) if event.slideshow_image?
        %td= truncate(event.slideshow_description, length: 50, separator: ' ')
        %td= l event.start_date, format: :short
        %td= l event.end_date, format: :short
        %td
          = link_to 'Editer', edit_event_path(event)
        %td
          = link_to 'Supprimer', event, :method => :delete, :data => { :confirm => 'Êtes-vous sûr ?' }

%br

= link_to 'Nouvel Evénement', new_event_path

app/views/events/display.html.haml
#events
  %h1
    - if params[:type].present?  
      = "Les #{t(params[:type]).pluralize}" 
    -else 
      Tous les évènements
  #content-block
    - @events.each do |event|
      %div.dotted
        = link_to event.title, event, class: "title"
        .from_to= "Du #{l(event.start_date, format: :short)} au #{l(event.end_date, format: :short)}"
        %p
          = event.short_description
        = link_to "Lire la suite", event, class: "link"


  #right-side-block
    = @event_clndr.view(id:'event-calendar')

    #filter-links
      - if params[:type] == "exhibition"
        = link_to "Les expositions à venir", display_events_path(type: "exhibition")
        = link_to "Les expositions passées", display_events_path(type: "exhibition", in_time: "past")
      - elsif params[:type] == "event"
        = link_to "Les évènements à venir", display_events_path(type: "event")
        = link_to "Les évènements passés", display_events_path(type: "event", in_time: "past")
      - else
        = link_to "Les évènements à venir", display_events_path
        = link_to "Les évènements passés", display_events_path(in_time: "past")
  

  .clear

app/views/events/edit.html.haml
= render 'form'

= link_to 'Back', events_path

app/views/events/new.html.haml
= render 'form'

= link_to 'Back', admins_path

app/views/events/show.html.haml
#events
  %h1= @event.title
  #content-block
    .center
      = image_tag(@event.slideshow_image_url, width: "500px") if @event.slideshow_image?
    %p= format_text(@event.description)

  #right-side-block
    = @event_clndr.view(id:'event-calendar')

    #filter-links
      - if params[:type] == "exhibition"
        = link_to "Les expositions à venir", display_events_path(type: "exhibition")
        = link_to "Les expositions passées", display_events_path(type: "exhibition", in_time: "past")
      - else params[:type] == "event"
        = link_to "Les évènements à venir", display_events_path(type: "event")
        = link_to "Les évènements passés", display_events_path(type: "event", in_time: "past")


  .clear